services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bnck-codeflix-java-image:latest
    container_name: bnck-codeflix-java
    volumes:
      - .:/app
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m

